name: keepalive
on:
  schedule:
    - cron: "*/12 * * * *"   # a cada 12 minutos
  workflow_dispatch:        # permite rodar manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Render URL
        env:
          APP_URL: ${{ secrets.RENDER_APP_URL }}
        run: |
          # ping no root; Streamlit responde a qualquer path
          curl -m 10 -sS -o /dev/null -w "%{http_code}\n" "${APP_URL}" || true
